import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import classification_report, accuracy_score
import datetime
import warnings
warnings.filterwarnings('ignore')

from sqlalchemy import create_engine

import json

def load_data_from_json():
    """Loads simulation data from JSON files generated by data_generator."""
    print("Loading data from generated JSON files (Maharashtra Simulation)...")
    
    try:
        with open("departments.json", "r") as f:
            depts_data = json.load(f)
        df_depts = pd.DataFrame(depts_data)
        
        with open("vendors.json", "r") as f:
            vendors_data = json.load(f)
        df_vendors = pd.DataFrame(vendors_data)
        
        with open("transactions.json", "r") as f:
            tx_data = json.load(f)
        df_tx = pd.DataFrame(tx_data)
        
        # Ensure timestamp is datetime and quarter is extracted
        df_tx['timestamp'] = pd.to_datetime(df_tx['timestamp'])
        df_tx['quarter'] = df_tx['timestamp'].dt.quarter
        
        return df_depts, df_vendors, df_tx
        
    except FileNotFoundError:
        print("Error: JSON files not found. Please run data_generator.py first.")
        return None, None, None

def fetch_data_from_db(db_uri):
    """Fetches data from the actual database tables using SQLAlchemy."""
    print(f"Connecting to database at {db_uri}...")
    try:
        engine = create_engine(db_uri)
        
        print("Fetching 'departments' table...")
        df_depts = pd.read_sql_table("departments", con=engine)
        
        print("Fetching 'vendors' table...")
        df_vendors = pd.read_sql_table("vendors", con=engine)
        
        print("Fetching 'transactions' table...")
        df_tx = pd.read_sql_table("transactions", con=engine)
        
        # Ensure timestamp is datetime and quarter is extracted
        df_tx['timestamp'] = pd.to_datetime(df_tx['timestamp'])
        df_tx['quarter'] = df_tx['timestamp'].dt.quarter
        
        return df_depts, df_vendors, df_tx
        
    except Exception as e:
        print(f"Error connecting to database or fetching tables: {e}")
        print("Please ensure your database is running and the tables 'departments', 'vendors', and 'transactions' exist with the correct schema.")
        return None, None, None

def feature_engineering(df_depts, df_tx):
    """Engineers features required for predictive modeling."""
    print("Engineering features...")

    # utilized_budget is already present in df_depts in the new JSON data structure!
    # Feature 1: Utilization Rate
    df_final = df_depts.copy()
    df_final['utilization_rate'] = df_final['utilized_budget'] / df_final['allocated_budget']

    # Feature 2: Spending Velocity (Quarterly spending percentage)
    q_spending = df_tx.pivot_table(index='dept_id', columns='quarter', values='amount', aggfunc='sum', fill_value=0)
    q_spending.columns = [f'Q{int(c)}_spending' for c in q_spending.columns]
    
    df_final = pd.merge(df_final, q_spending, on='dept_id', how='left').fillna(0)
    
    # Convert quarterly absolute spending to percentage of allocated budget
    for q in range(1, 5):
        col_name = f'Q{q}_spending'
        pct_col_name = f'Q{q}_pct'
        if col_name in df_final.columns:
            df_final[pct_col_name] = df_final[col_name] / df_final['allocated_budget']
        else:
            df_final[pct_col_name] = 0.0

    # Synthetic Target Variable creation (for prototype purposes)
    # Ensure there are multiple classes by using the median
    median_util = df_final['utilization_rate'].median()
    # Add some randomness or use a balanced threshold
    df_final['actual_lapse'] = (df_final['utilization_rate'] < median_util).astype(int)
    
    return df_final

def train_predictive_model(df):
    """Trains models to predict fund lapse risk and exact spending amount."""
    print("Training Random Forest models (Classification & Regression)...")
    
    features = [
        'allocated_budget', 
        'historical_utilization_pct', 
        'project_delays',
        'utilization_rate',
        'Q1_pct', 'Q2_pct', 'Q3_pct', 'Q4_pct'
    ]
    
    X = df[features]
    y_class = df['actual_lapse']
    y_reg = df['utilized_budget']
    
    X_train, X_test, _, y_class_test, indices_train, indices_test = train_test_split(
        X, y_class, df.index, test_size=0.25, random_state=42, stratify=y_class
    )
    y_reg_train = y_reg.loc[indices_train]
    y_reg_test = y_reg.loc[indices_test]

    # Model 1: Classifier
    clf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
    clf.fit(X_train, y_class.loc[indices_train])
    y_class_pred = clf.predict(X_test)
    y_prob = clf.predict_proba(X_test)[:, 1]
    
    # Model 2: Regressor
    reg = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)
    reg.fit(X_train, y_reg_train)
    y_reg_pred = reg.predict(X_test)

    print("\n--- Model Evaluation ---")
    print("Classification (Risk of Lapsing):")
    print(classification_report(y_class_test, y_class_pred, target_names=["No Lapse", "Lapse"]))
    
    # Simple evaluation for regression
    from sklearn.metrics import mean_absolute_error
    mae = mean_absolute_error(y_reg_test, y_reg_pred)
    print(f"Regression (Predicted Final Spend MAE): Rs. {mae:,.2f}")

    results_df = df.loc[indices_test].copy()
    results_df['predicted_risk_class'] = y_class_pred
    results_df['lapse_probability'] = y_prob
    results_df['predicted_utilized_budget'] = y_reg_pred
    results_df['predicted_lapse_amount'] = np.maximum(0, results_df['allocated_budget'] - results_df['predicted_utilized_budget'])

    # Next Year Budget Prediction Logic
    # We base next year's budget on:
    # 1. How much they actually needed this year (predicted final spend)
    # 2. A growth factor (let's say 5-10% standard increase for inflation/expansion)
    # 3. Penalize departments that consistently lapse by reducing growth.
    
    def calculate_next_budget(row):
        base_need = row['predicted_utilized_budget']
        
        # If they are very efficient (low lapse prob and good history), give them 10% more than what they utilized
        if row['lapse_probability'] < 0.3 and row['historical_utilization_pct'] > 0.8:
            return base_need * 1.10
        # If they are very inefficient (high lapse prob), only give them a 2% buffer above their actual spend
        elif row['lapse_probability'] > 0.7:
            return base_need * 1.02
        # Otherwise, standard 5% growth
        else:
            return base_need * 1.05

    results_df['recommended_next_budget'] = results_df.apply(calculate_next_budget, axis=1)

    return clf, results_df

def generate_risk_alerts(results_df):
    """Outputs early warning system logs based on model predictions."""
    from tabulate import tabulate
    print("\n================ FUND LAPSE PREDICTIONS ================\n")
    
    # Sort by highest probability of lapsing
    risky_depts = results_df.sort_values(by='lapse_probability', ascending=False)
    
    table_data = []
    headers = ["Department", "District", "Allocated (Rs.)", "Predicted Spend", "Est. Lapse Amount", "Lapse Risk", "Next Yr Recom. Budget"]
    
    # Show Top 10 riskiest departments in the table
    for _, row in risky_depts.head(10).iterrows():
        
        table_data.append([
            row['dept_name'].replace(" Dept", ""),
            row['district'],
            f"{row['allocated_budget']:,.0f}",
            f"{row['predicted_utilized_budget']:,.0f}",
            f"{row['predicted_lapse_amount']:,.0f}",
            f"{row['lapse_probability'] * 100:.1f}%",
            f"{row['recommended_next_budget']:,.0f} (+{((row['recommended_next_budget']/row['predicted_utilized_budget'])-1)*100:.0f}%)"
        ])
        
    print(tabulate(table_data, headers=headers, tablefmt="grid"))
    print("\n========================================================")

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Run the Fund Lapse Prediction Model")
    parser.add_argument("--db-uri", type=str, required=False, default=None, help="Database connection URI (Optional)")
    args = parser.parse_args()
    
    # 1. Pipeline Execution
    if args.db_uri:
        print("Step 1: Fetching data from database schemas...")
        df_depts, df_vendors, df_tx = fetch_data_from_db(args.db_uri)
        if df_depts is None:
            print("Pipeline aborted due to data fetch error.")
            exit(1)
    else:
        print("Step 1: No --db-uri provided. Falling back to generated JSON Data...")
        df_depts, df_vendors, df_tx = load_data_from_json()
        if df_depts is None:
            print("Pipeline aborted due to missing JSON files.")
            exit(1)
    
    print("\nStep 2: Performing Feature Engineering...")
    df_features = feature_engineering(df_depts, df_tx)
    
    print("\nStep 3: Training ML Model & Predicting...")
    model, predictions = train_predictive_model(df_features)
    
    print("\nStep 4: Generating Output & Dashboard Data...")
    generate_risk_alerts(predictions)
    
    # Optionally save to CSV for the dashboard
    df_features.to_csv("processed_dashboard_data.csv", index=False)
    print("\nPipeline complete. Data exported to 'processed_dashboard_data.csv'")
